version: "3.8"

services:
  frontend:
    build: .
    container_name: debit-frontend
    ports:
      - "3010:80"   # nginx -> container
    restart: unless-stopped
    environment:
      VITE_API_URL: http://62.72.21.81:3009
